---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink : /:year
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:       "Victoria Recycling Maps - Joe Burkinshaw & Bruce Mackenzie"
keywords:    "Victoria Recycling Maps, Recycling, Capital Region District, CRD, Victoria, Esquimalt, Oak Bay, James Bay, Saanich, Vic"
description: "A web page for the Victoria Recycling Maps project."
source_link: "https://github.com/t413/SinglePaged"
favicon:     img/favicon.ico
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: UA-39902836-2


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
